
using System.ComponentModel.DataAnnotations;


namespace VirtualClassroomDashboard.Models
{
    public class AnnouncementModel
    {
        //generated by database
        public int AnnounceID { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "Title is required")]
        //title of the announcement
        public string AnnounceTitle { get; set; }

        [Display(Name = "Announcement")]
        [Required(ErrorMessage = "Announcement is required")]
        //the content of the announcement
        public string AnnounceDesc { get; set; }

        //user (Teacher) and the course the announcement is for
        public int CourseID { get; set; }

        public int UserID { get; set; }

        //File Info
        [Display(Name = "Select File")]
        [Required(ErrorMessage = "Selecting a file is required")]
        public string FileName { get; set; }
        public string FIlePath { get; set; }
        [Display(Name = "File Subject")]
        [Required(ErrorMessage = "The File Subject is required")]
        public string FileSubject { get; set; }
        [Display(Name = "File Description")]
        [Required(ErrorMessage = "File Description is required")]
        public string FileDesc { get; set; }

        public int FileID { get; set; }
    }
}
