using System;
using System.ComponentModel.DataAnnotations;

namespace VirtualClassroomDashboard.Models
{
    public class DiscussionsModel
    {
        //generated by database
        public int DiscussionID { get; set; }

        [Display(Name = "Discussion Title")]
        [Required(ErrorMessage = "Discussion Title is required")]
        //title of the discussion
        public string DiscussionTitle { get; set; }

        [Display(Name = "Discussion Message")]
        [Required(ErrorMessage = "Discussion Message is required")]
        //message of the discussion
        public string DiscussionDesc { get; set; }
        //date comes from a framework
        public DateTime DiscussionDate { get; set; }
        //the current selected course
        public int CourseID { get; set; }
        //the id of the user
        public int UserID { get; set; }
    }
}
