using System;
using System.ComponentModel.DataAnnotations;

namespace VirtualClassroomDashboard.Models
{
    public class DiscussionReplyModel
    {
        //generated by database
        public int DiscussionReplyID { get; set; }

        [Display(Name = "Discussion Reply")]
        [Required(ErrorMessage = "Discussion Reply is required")]
        //message of the discussion
        public string DiscussionReplyDesc { get; set; }

        //generated by framework
        public String DiscussionReplyDate { get; set; }
        //comes from the  dicussion boaard that is being replied to 
        public int DiscussionID { get; set; }
        //this is the user who is replying 
        public int UserID { get; set; }
        //this is for display purposes
        public string UserName { get; set; }
    }
}
