CREATE TABLE SCHOOL(

	SchoolID INT NOT NULL,
	SchoolName VARCHAR(255) NOT NULL,
	SchoolLevel VARCHAR(20) NOT NULL,
	PRIMARY KEY (SchoolID)

);

CREATE TABLE USER_INFO (

	UserID INT NOT NULL,
	UserFname VARCHAR(255) NOT NULL,
	UserLname VARCHAR(255) NOT NULL,
	UserPhonNum VARCHAR(12) DEFAULT NULL,
	UserEmail VARCHAR(255) NOT NULL,
	UserLevel VARCHAR(8) NOT NULL,
	SchoolID INT NOT NULL,
	PRIMARY KEY (UserID),
	FOREIGN KEY (SchoolID) REFERENCES SCHOOL(SchoolID)
);

CREATE TABLE COURSES (

	CourseID INT NOT NULL,
	CourseName VARCHAR(100) NOT NULL,
	CourseSection INT NOT NULL,
	CourseNumber VARCHAR(20) NOT NULL,
	ClassNum INT NOT NULL,
	UserID INT NOT NULL,
	SchoolID INT NOT NULL,
	PRIMARY KEY (CourseID),
	FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID),
	FOREIGN KEY (SchoolID) REFERENCES SCHOOL(SchoolID)

);

CREATE TABLE USER_COURSE(

	UserID INT NOT NULL,
	CourseID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID),
	FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID),
	CONSTRAINT VCD_UC_CONST1 UNIQUE (UserID, CourseID)

);

CREATE TABLE ASSIGNMENTS(

	AssignID INT NOT NULL,
	AssignName VARCHAR(255) NOT NULL,
	AssignDate DATE NOT NULL,
	AssignDueDate DATETIME DEFAULT NULL,
	AssignDescription VARCHAR(1000) DEFAULT NULL,
	AssignFile VARCHAR(255) DEFAULT NULL,
	AssignPoints INT NOT NULL,
	AssignType VARCHAR(10) NOT NULL,
	CourseID INT NOT NULL,
	PRIMARY KEY (AssignID),
	FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID)

);

CREATE TABLE USER_ASSIGNMENT(

	AssignID INT NOT NULL,
	UserID INT NOT NULL,
	UserAssignFile VARCHAR(255) NOT NULL,
	UserAssignGrade INT DEFAULT NULL,
	FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID),
	FOREIGN KEY (AssignID) REFERENCES ASSIGNMENTS(AssignID),
	CONSTRAINT VCD_UA_CONST1 UNIQUE (UserID, AssignID)

);

CREATE TABLE ASSESSMENT (

	AssessID INT NOT NULL,
	AssessName VARCHAR(255) NOT NULL,
	AssessStartDate DATETIME NOT NULL,
	AssessEndSate  DATETIME NOT NULL,
	AssessTimeLimit INT NOT NULL,
	AssessPoints INT NOT NULL,
	AssessType VARCHAR(4) NOT NULL,
	CourseID INT NOT NULL,
	PRIMARY KEY (AssessID),
	FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID)

);

CREATE TABLE QUESTIONS (

	QuestionID INT NOT NULL,
	Question VARCHAR(255) NOT NULL,
	QuestionImage VARCHAR(255) DEFAULT NULL,
	QuestionType VARCHAR(20) NOT NULL,
	AssessID INT NOT NULL,
	PRIMARY KEY (QuestionID),
	FOREIGN KEY (AssessID) REFERENCES ASSESSMENT(AssessID)

);

CREATE TABLE OPTIONS (

	OptionID INT NOT NULL,
	Options VARCHAR(255) NOT NULL,
	IsCorrect INT NOT NULL,
	QuestionID INT NOT NULL,
	PRIMARY KEY (OptionID),
	FOREIGN KEY (QuestionID) REFERENCES QUESTIONS(QuestionID)

);

CREATE TABLE ASSESSMENT_RESULT(

	AssessResultID INT NOT NULL,
	IsCorrect INT NOT NULL,
	AssessDescription VARCHAR(255) DEFAULT NULL,
	OptionID INT NOT NULL,
	QuestionID INT NOT NULL,
	UserID INT NOT NULL,
	PRIMARY KEY (AssessResultID),
	FOREIGN KEY (OptionID) REFERENCES OPTIONS(OptionID),
	FOREIGN KEY (QuestionID) REFERENCES QUESTIONS(QuestionID),
	FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID)

);

CREATE TABLE USER_ASSESS_RESULT(

	AssessID INT NOT NULL,
	UserID INT NOT NULL,
	UserAssessGrade INT DEFAULT NULL,
	FOREIGN KEY (AssessID) REFERENCES ASSESSMENT(AssessID),
	FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID), 
	CONSTRAINT VCD_UAR_CONST1 UNIQUE (AssessID, UserID)

);

CREATE TABLE GRADE_FORMAT(

	GradeFormatID INT NOT NULL,
	GradeFSection VARCHAR(20) NOT NULL,
	GradeFPercent VARCHAR(4) NOT NULL,
	CourseID INT NOT NULL,
	PRIMARY KEY (GradeFormatID),
	FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID)

);

CREATE TABLE GRADE (

	GradeID INT NOT NULL,
	GradePoints INT NOT NULL,
	GradePercent VARCHAR(4) NOT NULL,
	CourseID INT NOT NULL,
	UserID INT NOT NULL,
	PRIMARY KEY (GradeID),
	FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID),
	FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID)

);

CREATE TABLE ANNOUNCEMENTS (

	AnnounceID INT NOT NULL,
	AnnounceTitle VARCHAR(255) NOT NULL,
	AnnounceDesc VARCHAR(700) NOT NULL,
	CourseID INT NOT NULL,
	UserID INT NOT NULL,
	PRIMARY KEY (AnnounceID),
	FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID),
	FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID)
 
);

CREATE TABLE DISCUSSION (

	DiscussionID INT NOT NULL,
	DiscussionTitle VARCHAR(255) NOT NULL,
	DiscussionDesc VARCHAR(700) NOT NULL,
	DiscussionDate DATE NOT NULL,
	CourseID INT NOT NULL,
	UserID INT NOT NULL,
	PRIMARY KEY (DiscussionID),
	FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID),
	FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID)

);

CREATE TABLE DISCUSSION_REPLY(

	DiscussionReplyID INT NOT NULL,
	DiscussionReplyDesc VARCHAR(700) NOT NULL,
	DiscussionReplyDate DATE NOT NULL,
	DiscussionID INT NOT NULL,
	UserID INT NOT NULL,
	PRIMARY KEY (DiscussionReplyID),
	FOREIGN KEY (DiscussionID) REFERENCES DISCUSSION(DiscussionID),
	FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID)

);